name: Obfuscate and Deploy to Pages

on:
  push:
    branches: ["main"] 
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Inject Secrets into script.js
        
        run: |
          sed -i "s|__SCRIPT_URL__|${{ secrets.SCRIPT_URL }}|g" script.js
          sed -i "s|__QR_LAT__|${{ secrets.QR_LAT }}|g" script.js
          sed -i "s|__QR_LON__|${{ secrets.QR_LON }}|g" script.js
          sed -i "s|__MAX_DIST__|${{ secrets.MAX_DIST }}|g" script.js

      - name: Install JavaScript Obfuscator
        run: npm install -g javascript-obfuscator

      - name: Scramble JavaScript
        # This  codes and arrays
        run: |
          javascript-obfuscator script.js --output script.js \
            --compact true \
            --control-flow-flattening true \
            --dead-code-injection true \
            --string-array true \
            --string-array-encoding 'base64' \
            --disable-console-output true

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4